version: "3.9"
services:
  api:
    build: ./core/api
    image: sky_axs_initial-api
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: unless-stopped
    command: ["bash","/app/start_uvicorn.sh"]
